name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check code format
      run: cargo fmt -- --check
  
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Check
      run: cargo check --verbose --all-targets

  test:
    runs-on: ubuntu-latest

    needs: check

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
